version: '3.9'

services:
  backend:
    container_name: tanalista-back

    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://tnl-db-instance.crsq7uooceaf.us-east-1.rds.amazonaws.com:3306/tanalista_db?useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: tnl_user
      SPRING_DATASOURCE_PASSWORD: Allrsm_2018

    ports:
      - "8088:8088"

    restart: always