-- INSERT DE CATEGORIAS 
INSERT INTO categoria (codigo, nome, criado_em, atualizado_em, deletado) VALUES
('BEBIDAS', 'Bebidas', NOW(), NOW(), false),
('CARNES', 'Carnes', NOW(), NOW(), false),
('PADARIA', 'Padaria', NOW(), NOW(), false),
('HORTIFRUTI', 'Hortifruti', NOW(), NOW(), false),
('LATICINIOS', 'Laticínios', NOW(), NOW(), false),
('MERCEARIA', 'Mercearia', NOW(), NOW(), false),
('HIGIENE', 'Higiene', NOW(), NOW(), false),
('LIMPEZA', 'Limpeza', NOW(), NOW(), false),
('PETS', 'Pets', NOW(), NOW(), false),
('DOCES', 'Doces', NOW(), NOW(), false),
('UTILIDADES', 'Utilidades', NOW(), NOW(), false),
('BEBES', 'Bebês', NOW(), NOW(), false),
('SAZONAIS', 'Sazonais', NOW(), NOW(), false);
-- /////////////////////////////////////////////////////////
-- INSERT DE PRODUTOS
-- /////////////////////////////////////////////////////////

-- BEBIDADAS 🍺
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Refrigerante Cola 2L', 'Sabor cola tradicional', 1, NOW(), NOW()),
('Refrigerante Cola Zero 2L', 'Sem açúcar', 1, NOW(), NOW()),
('Refrigerante Cola Lata 350ml', 'Porção individual', 1, NOW(), NOW()),
('Refrigerante Guaraná 2L', 'Sabor nacional clássico', 1, NOW(), NOW()),
('Refrigerante Guaraná Zero', 'Sem açúcar', 1, NOW(), NOW()),
('Refrigerante Laranja 2L', 'Sabor cítrico', 1, NOW(), NOW()),
('Refrigerante Limão 2L', 'Refrescante', 1, NOW(), NOW()),
('Refrigerante Uva 2L', 'Sabor doce', 1, NOW(), NOW()),
('Refrigerante Tônica 1L', 'Amargo leve', 1, NOW(), NOW()),
('Água Mineral 500ml', 'Sem gás', 1, NOW(), NOW()),
('Água Mineral 1.5L', 'Sem gás', 1, NOW(), NOW()),
('Água Mineral 5L', 'Galão', 1, NOW(), NOW()),
('Água com Gás 500ml', 'Gaseificada', 1, NOW(), NOW()),
('Água com Gás 1.5L', 'Gaseificada', 1, NOW(), NOW()),
('Água de Coco 200ml', 'Natural hidratante', 1, NOW(), NOW()),
('Água de Coco 1L', 'Natural', 1, NOW(), NOW()),
('Suco de Laranja 1L', 'Natural integral', 1, NOW(), NOW()),
('Suco de Laranja 300ml', 'Individual', 1, NOW(), NOW()),
('Suco de Uva Integral 1L', '100% fruta', 1, NOW(), NOW()),
('Suco de Maçã 1L', 'Doce leve', 1, NOW(), NOW()),
('Suco de Abacaxi 1L', 'Tropical', 1, NOW(), NOW()),
('Suco de Manga 1L', 'Doce natural', 1, NOW(), NOW()),
('Suco de Pêssego 1L', 'Suave', 1, NOW(), NOW()),
('Suco de Maracujá 1L', 'Relaxante', 1, NOW(), NOW()),
('Suco de Caju 1L', 'Nordeste', 1, NOW(), NOW()),
('Suco de Acerola 1L', 'Vitamina C', 1, NOW(), NOW()),
('Suco Detox Verde 500ml', 'Saudável', 1, NOW(), NOW()),
('Chá Gelado Limão 1L', 'Pronto consumo', 1, NOW(), NOW()),
('Chá Gelado Pêssego 1L', 'Refrescante', 1, NOW(), NOW()),
('Chá Verde 500ml', 'Saudável', 1, NOW(), NOW()),
('Chá Mate Gelado 1L', 'Tradicional', 1, NOW(), NOW()),
('Energético 250ml', 'Cafeína alta', 1, NOW(), NOW()),
('Energético 473ml', 'Tamanho grande', 1, NOW(), NOW()),
('Isotônico Azul 500ml', 'Reposição eletrólitos', 1, NOW(), NOW()),
('Isotônico Laranja 500ml', 'Hidratação esportiva', 1, NOW(), NOW()),
('Café Gelado 330ml', 'Pronto beber', 1, NOW(), NOW()),
('Achocolatado Líquido 1L', 'Doce pronto', 1, NOW(), NOW()),
('Leite com Chocolate 200ml', 'Individual', 1, NOW(), NOW()),
('Cerveja Sem Álcool 350ml', 'Refrescante', 1, NOW(), NOW()),
('Água Tônica 1L', 'Mixer', 1, NOW(), NOW()),
('Refrigerante Citrus 2L', 'Cítrico especial', 1, NOW(), NOW()),
('Refrigerante Cola Diet 2L', 'Zero açúcar', 1, NOW(), NOW()),
('Suco de Morango 1L', 'Frutado doce', 1, NOW(), NOW()),
('Suco de Frutas Vermelhas 1L', 'Mistura berries', 1, NOW(), NOW()),
('Bebida Energética Tropical 250ml', 'Energia exótica', 1, NOW(), NOW()),
('Bebida Energética Citrus 250ml', 'Refrescante energético', 1, NOW(), NOW()),
('Milkshake Chocolate 300ml', 'Pronto consumo', 1, NOW(), NOW()),
('Milkshake Morango 300ml', 'Doce cremoso', 1, NOW(), NOW());

-- CARNES 🥩
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Picanha Premium', 'Corte nobre bovino ideal para churrasco', 2, NOW(), NOW()),
('Picanha Angus', 'Carne macia de alta qualidade', 2, NOW(), NOW()),
('Alcatra Bovina', 'Corte versátil e macio', 2, NOW(), NOW()),
('Contra-filé', 'Sabor intenso para grelha', 2, NOW(), NOW()),
('Maminha', 'Corte suave e suculento', 2, NOW(), NOW()),
('Filé Mignon', 'Corte nobre extremamente macio', 2, NOW(), NOW()),
('Fraldinha', 'Ideal para churrasco', 2, NOW(), NOW()),
('Acém', 'Corte econômico para cozidos', 2, NOW(), NOW()),
('Patinho', 'Carne magra moída ou em bifes', 2, NOW(), NOW()),
('Carne Moída Acém', 'Versátil para receitas', 2, NOW(), NOW()),
('Carne Moída Patinho', 'Mais magra', 2, NOW(), NOW()),
('Cupim', 'Corte bovino gorduroso e macio', 2, NOW(), NOW()),
('Ossobuco', 'Ideal para cozidos e molhos', 2, NOW(), NOW()),
('Costela Bovina', 'Para churrasco e forno', 2, NOW(), NOW()),
('Costela Suína', 'Sabor intenso e suculento', 2, NOW(), NOW()),
('Pernil Suíno', 'Assados e churrascos', 2, NOW(), NOW()),
('Lombo Suíno', 'Corte magro e leve', 2, NOW(), NOW()),
('Bisteca Suína', 'Fácil preparo', 2, NOW(), NOW()),
('Filé de Frango', 'Peito sem osso e sem pele', 2, NOW(), NOW()),
('Peito de Frango', 'Versátil e magro', 2, NOW(), NOW()),
('Coxa de Frango', 'Sabor mais intenso', 2, NOW(), NOW()),
('Sobrecoxa de Frango', 'Ideal para forno', 2, NOW(), NOW()),
('Asa de Frango', 'Petisco e churrasco', 2, NOW(), NOW()),
('Drumet de Frango', 'Parte inferior da asa', 2, NOW(), NOW()),
('Frango Inteiro', 'Ideal para assados', 2, NOW(), NOW()),
('Linguiça Toscana', 'Temperada para churrasco', 2, NOW(), NOW()),
('Linguiça Calabresa', 'Defumada e saborosa', 2, NOW(), NOW()),
('Linguiça de Frango', 'Mais leve', 2, NOW(), NOW()),
('Linguiça Artesanal', 'Produção caseira', 2, NOW(), NOW()),
('Hambúrguer Bovino', 'Pronto para grelha', 2, NOW(), NOW()),
('Hambúrguer de Frango', 'Mais leve', 2, NOW(), NOW()),
('Hambúrguer Artesanal', 'Blend especial', 2, NOW(), NOW()),
('Carne de Sol', 'Curada e salgada', 2, NOW(), NOW()),
('Charque', 'Carne salgada tradicional', 2, NOW(), NOW()),
('Coração de Frango', 'Muito usado em churrasco', 2, NOW(), NOW()),
('Fígado Bovino', 'Rico em ferro', 2, NOW(), NOW()),
('Rim Bovino', 'Uso culinário específico', 2, NOW(), NOW()),
('Filé de Peixe Tilápia', 'Leve e saudável', 2, NOW(), NOW()),
('Filé de Salmão', 'Corte nobre de peixe', 2, NOW(), NOW()),
('Sardinha Fresca', 'Peixe popular', 2, NOW(), NOW()),
('Atum Fresco', 'Corte de peixe nobre', 2, NOW(), NOW()),
('Camarão Limpo', 'Frutos do mar', 2, NOW(), NOW()),
('Carne Suína Moída', 'Versátil', 2, NOW(), NOW()),
('Carne Bovina para Ensopado', 'Cortes variados', 2, NOW(), NOW());

-- PADARIA 🥖
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Pão Francês', 'Tradicional pão de padaria', 3, NOW(), NOW()),
('Pão Francês Integral', 'Versão mais saudável', 3, NOW(), NOW()),
('Pão de Forma Tradicional', 'Ideal para sanduíches', 3, NOW(), NOW()),
('Pão de Forma Integral', 'Com fibras', 3, NOW(), NOW()),
('Pão de Leite', 'Macio e levemente doce', 3, NOW(), NOW()),
('Pão Australiano', 'Escuro e adocicado', 3, NOW(), NOW()),
('Pão Brioche', 'Massa amanteigada', 3, NOW(), NOW()),
('Baguete Tradicional', 'Longo e crocante', 3, NOW(), NOW()),
('Baguete Integral', 'Versão saudável', 3, NOW(), NOW()),
('Croissant Simples', 'Folhado amanteigado', 3, NOW(), NOW()),
('Croissant Chocolate', 'Recheado com chocolate', 3, NOW(), NOW()),
('Croissant Presunto e Queijo', 'Salgado recheado', 3, NOW(), NOW()),
('Sonho de Creme', 'Recheado com creme', 3, NOW(), NOW()),
('Sonho de Doce de Leite', 'Recheio doce', 3, NOW(), NOW()),
('Rosquinha de Açúcar', 'Clássica de padaria', 3, NOW(), NOW()),
('Rosquinha de Coco', 'Cobertura doce', 3, NOW(), NOW()),
('Rosca Doce', 'Massa tradicional', 3, NOW(), NOW()),
('Rosca de Canela', 'Aromática e doce', 3, NOW(), NOW()),
('Pão de Queijo Tradicional', 'Mineiro clássico', 3, NOW(), NOW()),
('Pão de Queijo Recheado', 'Com queijo extra', 3, NOW(), NOW()),
('Bolo de Chocolate', 'Fatia tradicional', 3, NOW(), NOW()),
('Bolo de Cenoura com Chocolate', 'Clássico brasileiro', 3, NOW(), NOW()),
('Bolo de Fubá', 'Caseiro simples', 3, NOW(), NOW()),
('Bolo de Laranja', 'Cítrico e leve', 3, NOW(), NOW()),
('Bolo de Coco', 'Doce e úmido', 3, NOW(), NOW()),
('Bolo Formigueiro', 'Com granulado', 3, NOW(), NOW()),
('Torta de Frango', 'Salgada tradicional', 3, NOW(), NOW()),
('Torta de Presunto e Queijo', 'Recheio clássico', 3, NOW(), NOW()),
('Esfiha de Carne', 'Salgado assado', 3, NOW(), NOW()),
('Esfiha de Queijo', 'Versão leve', 3, NOW(), NOW()),
('Esfiha de Frango', 'Recheio de frango', 3, NOW(), NOW()),
('Coxinha de Frango', 'Frita tradicional', 3, NOW(), NOW()),
('Risole de Carne', 'Salgado empanado', 3, NOW(), NOW()),
('Kibe Frito', 'Temperado com trigo', 3, NOW(), NOW()),
('Kibe Assado', 'Versão mais leve', 3, NOW(), NOW()),
('Empada de Frango', 'Massa quebradiça', 3, NOW(), NOW()),
('Empada de Palmito', 'Recheio leve', 3, NOW(), NOW()),
('Donut Chocolate', 'Doce americano', 3, NOW(), NOW()),
('Donut Açúcar', 'Simples e doce', 3, NOW(), NOW()),
('Muffin de Chocolate', 'Mini bolo', 3, NOW(), NOW()),
('Muffin de Blueberry', 'Frutas vermelhas', 3, NOW(), NOW()),
('Torrada Integral', 'Crocante e leve', 3, NOW(), NOW()),
('Biscoito Caseiro Doce', 'Tradicional', 3, NOW(), NOW()),
('Biscoito Salgado', 'Snack leve', 3, NOW(), NOW()),
('Panetone Tradicional', 'Natalino', 3, NOW(), NOW()),
('Chocotone', 'Com gotas de chocolate', 3, NOW(), NOW()),
('Bolo Red Velvet', 'Especial de vitrine', 3, NOW(), NOW()),
('Pão Sírio', 'Massa leve', 3, NOW(), NOW()),
('Wrap de Pão Folhado', 'Moderno', 3, NOW(), NOW());

-- HORTIFRUTI 🍇
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Banana Prata', 'Fruta doce e popular', 4, NOW(), NOW()),
('Banana Nanica', 'Mais macia e doce', 4, NOW(), NOW()),
('Maçã Vermelha', 'Fruta crocante e doce', 4, NOW(), NOW()),
('Maçã Verde', 'Sabor ácido leve', 4, NOW(), NOW()),
('Laranja Pera', 'Cítrica e suculenta', 4, NOW(), NOW()),
('Laranja Bahia', 'Mais doce e sem sementes', 4, NOW(), NOW()),
('Limão Tahiti', 'Ácido e versátil', 4, NOW(), NOW()),
('Limão Siciliano', 'Aromático', 4, NOW(), NOW()),
('Abacaxi Pérola', 'Doce e suculento', 4, NOW(), NOW()),
('Abacaxi Havaí', 'Mais ácido', 4, NOW(), NOW()),
('Melancia', 'Refrescante e grande', 4, NOW(), NOW()),
('Melão Amarelo', 'Doce e leve', 4, NOW(), NOW()),
('Mamão Papaia', 'Digestivo natural', 4, NOW(), NOW()),
('Mamão Formosa', 'Maior e firme', 4, NOW(), NOW()),
('Uva Roxa', 'Doce sem caroço', 4, NOW(), NOW()),
('Uva Verde', 'Levemente ácida', 4, NOW(), NOW()),
('Morango Bandeja', 'Fruta delicada', 4, NOW(), NOW()),
('Manga Palmer', 'Doce e grande', 4, NOW(), NOW()),
('Manga Tommy', 'Firme e suculenta', 4, NOW(), NOW()),
('Pera', 'Fruta suave', 4, NOW(), NOW()),
('Kiwi', 'Ácido e nutritivo', 4, NOW(), NOW()),
('Goiaba', 'Doce e aromática', 4, NOW(), NOW()),
('Caju', 'Fruta tropical', 4, NOW(), NOW()),
('Acerola', 'Rica em vitamina C', 4, NOW(), NOW()),
('Maracujá', 'Azedo e calmante', 4, NOW(), NOW()),
('Coco Verde', 'Água natural', 4, NOW(), NOW()),
('Coco Seco', 'Uso culinário', 4, NOW(), NOW()),
('Abóbora Moranga', 'Culinária salgada', 4, NOW(), NOW()),
('Abóbora Cabotiá', 'Mais firme', 4, NOW(), NOW()),
('Batata Inglesa', 'Base de muitas receitas', 4, NOW(), NOW()),
('Batata Doce', 'Saudável e energética', 4, NOW(), NOW()),
('Cenoura', 'Rica em vitaminas', 4, NOW(), NOW()),
('Beterraba', 'Nutritiva e doce', 4, NOW(), NOW()),
('Alface Crespa', 'Folha fresca', 4, NOW(), NOW()),
('Alface Lisa', 'Folha leve', 4, NOW(), NOW()),
('Rúcula', 'Sabor amargo leve', 4, NOW(), NOW()),
('Espinafre', 'Nutritivo', 4, NOW(), NOW()),
('Couve Manteiga', 'Usada em sucos', 4, NOW(), NOW()),
('Brócolis', 'Vegetal nutritivo', 4, NOW(), NOW()),
('Couve-Flor', 'Versátil na cozinha', 4, NOW(), NOW()),
('Tomate Italiano', 'Base de molhos', 4, NOW(), NOW()),
('Tomate Salada', 'Fresco e firme', 4, NOW(), NOW()),
('Cebola Branca', 'Base culinária', 4, NOW(), NOW()),
('Cebola Roxa', 'Mais suave', 4, NOW(), NOW()),
('Alho', 'Tempero essencial', 4, NOW(), NOW()),
('Pimentão Vermelho', 'Doce e colorido', 4, NOW(), NOW()),
('Pimentão Verde', 'Sabor forte', 4, NOW(), NOW()),
('Pimentão Amarelo', 'Suave e doce', 4, NOW(), NOW()),
('Pepino', 'Refrescante', 4, NOW(), NOW()),
('Chuchu', 'Leve e neutro', 4, NOW(), NOW()),
('Vagem', 'Crocante e saudável', 4, NOW(), NOW());

-- LATICINIOS 🐮
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Leite Integral 1L', 'Leite tradicional', 5, NOW(), NOW()),
('Leite Desnatado 1L', 'Menos gordura', 5, NOW(), NOW()),
('Leite Semidesnatado 1L', 'Equilibrado', 5, NOW(), NOW()),
('Leite Zero Lactose 1L', 'Para intolerantes', 5, NOW(), NOW()),
('Leite em Pó Integral', 'Longa duração', 5, NOW(), NOW()),
('Leite Condensado', 'Doce concentrado', 5, NOW(), NOW()),
('Creme de Leite', 'Base para receitas', 5, NOW(), NOW()),
('Iogurte Natural', 'Sem açúcar', 5, NOW(), NOW()),
('Iogurte Morango', 'Sabor frutado', 5, NOW(), NOW()),
('Iogurte Banana', 'Doce leve', 5, NOW(), NOW()),
('Iogurte Grego', 'Mais cremoso', 5, NOW(), NOW()),
('Iogurte Zero Açúcar', 'Fitness', 5, NOW(), NOW()),
('Manteiga com Sal', 'Tradicional', 5, NOW(), NOW()),
('Manteiga sem Sal', 'Uso culinário', 5, NOW(), NOW()),
('Margarina Tradicional', 'Alternativa econômica', 5, NOW(), NOW()),
('Requeijão Cremoso', 'Para pães', 5, NOW(), NOW()),
('Requeijão Light', 'Menos gordura', 5, NOW(), NOW()),
('Queijo Mussarela Fatiado', 'Sanduíches', 5, NOW(), NOW()),
('Queijo Mussarela Peça', 'Versátil', 5, NOW(), NOW()),
('Queijo Prato', 'Sabor suave', 5, NOW(), NOW()),
('Queijo Minas Frescal', 'Leve e fresco', 5, NOW(), NOW()),
('Queijo Minas Padrão', 'Mais firme', 5, NOW(), NOW()),
('Queijo Parmesão Ralado', 'Para massas', 5, NOW(), NOW()),
('Queijo Parmesão Peça', 'Curado', 5, NOW(), NOW()),
('Queijo Cheddar', 'Sabor forte', 5, NOW(), NOW()),
('Queijo Gorgonzola', 'Azul intenso', 5, NOW(), NOW()),
('Queijo Brie', 'Macio e sofisticado', 5, NOW(), NOW()),
('Queijo Camembert', 'Cremoso', 5, NOW(), NOW()),
('Queijo Coalho', 'Churrasco', 5, NOW(), NOW()),
('Queijo Provolone', 'Defumado', 5, NOW(), NOW()),
('Ricota Fresca', 'Leve e saudável', 5, NOW(), NOW()),
('Doce de Leite', 'Tradicional brasileiro', 5, NOW(), NOW()),
('Bebida Láctea Chocolate', 'Pronto consumo', 5, NOW(), NOW()),
('Bebida Láctea Morango', 'Sabor doce', 5, NOW(), NOW()),
('Leite Fermentado', 'Probiótico', 5, NOW(), NOW()),
('Nata Fresca', 'Cremosa', 5, NOW(), NOW()),
('Creme de Ricota', 'Mais leve', 5, NOW(), NOW()),
('Queijo Cottage', 'Fitness', 5, NOW(), NOW());

-- MERCEARIA 🍚
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Arroz Branco 5kg', 'Tipo agulhinha tradicional', 6, NOW(), NOW()),
('Arroz Integral 1kg', 'Mais fibras e saudável', 6, NOW(), NOW()),
('Arroz Parboilizado 5kg', 'Mais soltinho após cozimento', 6, NOW(), NOW()),
('Feijão Carioca 1kg', 'Mais consumido no Brasil', 6, NOW(), NOW()),
('Feijão Preto 1kg', 'Base da feijoada', 6, NOW(), NOW()),
('Feijão Fradinho 1kg', 'Nordestino tradicional', 6, NOW(), NOW()),
('Lentilha 500g', 'Rica em proteína vegetal', 6, NOW(), NOW()),
('Grão de Bico 500g', 'Nutritivo e versátil', 6, NOW(), NOW()),
('Macarrão Espaguete', 'Massa longa tradicional', 6, NOW(), NOW()),
('Macarrão Penne', 'Ideal para molhos', 6, NOW(), NOW()),
('Macarrão Parafuso', 'Versátil para saladas', 6, NOW(), NOW()),
('Macarrão Instantâneo', 'Rápido preparo', 6, NOW(), NOW()),
('Molho de Tomate Tradicional', 'Base para receitas', 6, NOW(), NOW()),
('Molho de Tomate Temperado', 'Com ervas', 6, NOW(), NOW()),
('Extrato de Tomate', 'Concentrado', 6, NOW(), NOW()),
('Milho Verde Lata', 'Enlatado clássico', 6, NOW(), NOW()),
('Ervilha Lata', 'Complemento de receitas', 6, NOW(), NOW()),
('Sardinha em Lata', 'Proteína prática', 6, NOW(), NOW()),
('Atum em Lata', 'Alta proteína', 6, NOW(), NOW()),
('Azeite de Oliva 500ml', 'Extra virgem', 6, NOW(), NOW()),
('Óleo de Soja 900ml', 'Uso diário', 6, NOW(), NOW()),
('Óleo de Girassol 900ml', 'Mais leve', 6, NOW(), NOW()),
('Vinagre Branco', 'Uso culinário', 6, NOW(), NOW()),
('Vinagre de Maçã', 'Mais suave', 6, NOW(), NOW()),
('Sal Refinado 1kg', 'Uso geral', 6, NOW(), NOW()),
('Sal Grosso', 'Churrasco', 6, NOW(), NOW()),
('Açúcar Refinado 1kg', 'Uso geral', 6, NOW(), NOW()),
('Açúcar Cristal 1kg', 'Culinária', 6, NOW(), NOW()),
('Açúcar Mascavo', 'Mais natural', 6, NOW(), NOW()),
('Café Tradicional 500g', 'Torrado e moído', 6, NOW(), NOW()),
('Café Forte 500g', 'Sabor intenso', 6, NOW(), NOW()),
('Farinha de Trigo 1kg', 'Base para massas', 6, NOW(), NOW()),
('Farinha de Mandioca', 'Farofas', 6, NOW(), NOW()),
('Fubá de Milho', 'Culinária tradicional', 6, NOW(), NOW()),
('Polvilho Doce', 'Receitas brasileiras', 6, NOW(), NOW()),
('Polvilho Azedo', 'Pão de queijo', 6, NOW(), NOW()),
('Fermento Biológico', 'Massas e pães', 6, NOW(), NOW()),
('Fermento Químico', 'Bolos', 6, NOW(), NOW()),
('Leite de Coco', 'Culinária tropical', 6, NOW(), NOW()),
('Leite Condensado', 'Doces', 6, NOW(), NOW()),
('Creme de Leite', 'Molhos e sobremesas', 6, NOW(), NOW()),
('Chocolate em Pó 50%', 'Culinária', 6, NOW(), NOW()),
('Achocolatado em Pó', 'Bebida doce', 6, NOW(), NOW()),
('Gelatina Morango', 'Sobremesa rápida', 6, NOW(), NOW()),
('Gelatina Uva', 'Sobremesa leve', 6, NOW(), NOW()),
('Gelatina Limão', 'Refrescante', 6, NOW(), NOW()),
('Mistura para Bolo Chocolate', 'Prático', 6, NOW(), NOW()),
('Mistura para Bolo Baunilha', 'Fácil preparo', 6, NOW(), NOW()),
('Caldo de Galinha Cubos', 'Tempero concentrado', 6, NOW(), NOW()),
('Caldo de Carne Cubos', 'Base de sabor', 6, NOW(), NOW()),
('Temperos Secos Sortidos', 'Ervas e especiarias', 6, NOW(), NOW());

-- HIGIENE 🧻
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Sabonete em Barra Tradicional', 'Uso diário para banho', 7, NOW(), NOW()),
('Sabonete em Barra Hidratante', 'Com hidratação extra', 7, NOW(), NOW()),
('Sabonete Líquido Refil', 'Mais econômico', 7, NOW(), NOW()),
('Sabonete Íntimo Feminino', 'Uso específico', 7, NOW(), NOW()),
('Shampoo Anticaspa', 'Controle de caspa', 7, NOW(), NOW()),
('Shampoo Hidratante', 'Cabelos secos', 7, NOW(), NOW()),
('Shampoo para Cabelos Oleosos', 'Controle de oleosidade', 7, NOW(), NOW()),
('Condicionador Hidratante', 'Maciez e brilho', 7, NOW(), NOW()),
('Condicionador Reparador', 'Reconstrução capilar', 7, NOW(), NOW()),
('Creme Dental Tradicional', 'Proteção diária', 7, NOW(), NOW()),
('Creme Dental Branqueador', 'Clareamento', 7, NOW(), NOW()),
('Creme Dental Sensibilidade', 'Dentes sensíveis', 7, NOW(), NOW()),
('Escova de Dente Macia', 'Uso diário', 7, NOW(), NOW()),
('Escova de Dente Média', 'Limpeza eficiente', 7, NOW(), NOW()),
('Fio Dental 50m', 'Higiene interdental', 7, NOW(), NOW()),
('Enxaguante Bucal', 'Hálito fresco', 7, NOW(), NOW()),
('Desodorante Aerosol', 'Proteção 48h', 7, NOW(), NOW()),
('Desodorante Roll-on', 'Uso diário', 7, NOW(), NOW()),
('Desodorante Stick', 'Secagem rápida', 7, NOW(), NOW()),
('Papel Higiênico 4 rolos', 'Folha simples', 7, NOW(), NOW()),
('Papel Higiênico 12 rolos', 'Família', 7, NOW(), NOW()),
('Papel Higiênico Folha Dupla', 'Mais conforto', 7, NOW(), NOW()),
('Absorvente Noturno', 'Fluxo intenso', 7, NOW(), NOW()),
('Absorvente Diário', 'Uso leve', 7, NOW(), NOW()),
('Lenço Umedecido', 'Higiene rápida', 7, NOW(), NOW()),
('Algodão 50g', 'Uso dermatológico', 7, NOW(), NOW()),
('Cotonete', 'Limpeza delicada', 7, NOW(), NOW()),
('Álcool 70% 1L', 'Desinfecção', 7, NOW(), NOW()),
('Álcool Gel 500ml', 'Higienização das mãos', 7, NOW(), NOW()),
('Sabonete Antibacteriano', 'Proteção extra', 7, NOW(), NOW()),
('Sabonete Infantil', 'Pele sensível', 7, NOW(), NOW()),
('Shampoo Infantil', 'Uso delicado', 7, NOW(), NOW()),
('Condicionador Infantil', 'Cabelos infantis', 7, NOW(), NOW()),
('Pasta de Dente Infantil', 'Sabor suave', 7, NOW(), NOW()),
('Fralda Descartável M', 'Uso infantil', 7, NOW(), NOW()),
('Fralda Descartável G', 'Maior absorção', 7, NOW(), NOW()),
('Fralda Descartável XG', 'Alta capacidade', 7, NOW(), NOW()),
('Lenço de Papel', 'Uso diário', 7, NOW(), NOW()),
('Papel Toalha', 'Limpeza doméstica', 7, NOW(), NOW()),
('Sabonete Esfoliante', 'Cuidados com pele', 7, NOW(), NOW()),
('Creme Hidratante Corporal', 'Hidratação da pele', 7, NOW(), NOW()),
('Protetor Solar FPS 30', 'Proteção solar', 7, NOW(), NOW()),
('Protetor Solar FPS 50', 'Alta proteção', 7, NOW(), NOW()),
('Shampoo Antiqueda', 'Fortalecimento capilar', 7, NOW(), NOW());

-- LIMPEZA 🧼
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Detergente Neutro 500ml', 'Limpeza de louças', 8, NOW(), NOW()),
('Detergente Limão 500ml', 'Com aroma cítrico', 8, NOW(), NOW()),
('Detergente Maçã 500ml', 'Fragrância suave', 8, NOW(), NOW()),
('Sabão em Pó 1kg', 'Lavagem de roupas', 8, NOW(), NOW()),
('Sabão em Pó 2kg', 'Maior rendimento', 8, NOW(), NOW()),
('Sabão Líquido Roupas 1L', 'Mais delicado com tecidos', 8, NOW(), NOW()),
('Amaciante Concentrado 1L', 'Roupas macias', 8, NOW(), NOW()),
('Amaciante Lavanda 2L', 'Fragrância duradoura', 8, NOW(), NOW()),
('Água Sanitária 1L', 'Desinfecção pesada', 8, NOW(), NOW()),
('Água Sanitária 2L', 'Uso doméstico', 8, NOW(), NOW()),
('Desinfetante Floral 1L', 'Limpeza geral', 8, NOW(), NOW()),
('Desinfetante Lavanda 1L', 'Aroma suave', 8, NOW(), NOW()),
('Desinfetante Eucalipto 1L', 'Ação bactericida', 8, NOW(), NOW()),
('Limpador Multiuso 500ml', 'Superfícies gerais', 8, NOW(), NOW()),
('Limpador Vidros 500ml', 'Sem manchas', 8, NOW(), NOW()),
('Limpador Pesado 1L', 'Limpeza profunda', 8, NOW(), NOW()),
('Esponja de Cozinha', 'Dupla face', 8, NOW(), NOW()),
('Esponja Multiuso', 'Uso geral', 8, NOW(), NOW()),
('Esponja Aço 8 unidades', 'Remoção de sujeira pesada', 8, NOW(), NOW()),
('Pano de Chão Algodão', 'Limpeza de pisos', 8, NOW(), NOW()),
('Pano Microfibra', 'Alta absorção', 8, NOW(), NOW()),
('Rodo 40cm', 'Limpeza de piso', 8, NOW(), NOW()),
('Vassoura Cerdas Macias', 'Uso interno', 8, NOW(), NOW()),
('Vassoura Cerdas Duras', 'Área externa', 8, NOW(), NOW()),
('Pá de Lixo', 'Coleta de resíduos', 8, NOW(), NOW()),
('Balde 10L', 'Uso doméstico', 8, NOW(), NOW()),
('Balde 20L', 'Maior capacidade', 8, NOW(), NOW()),
('Lustra Móveis 200ml', 'Brilho e proteção', 8, NOW(), NOW()),
('Limpa Inox 300ml', 'Superfícies metálicas', 8, NOW(), NOW()),
('Limpa Forno 400ml', 'Desengordurante forte', 8, NOW(), NOW()),
('Desengordurante Cozinha 500ml', 'Gordura pesada', 8, NOW(), NOW()),
('Pedra Sanitária', 'Higienização banheiro', 8, NOW(), NOW()),
('Saboneteira de Limpeza', 'Organização banheiro', 8, NOW(), NOW()),
('Saco de Lixo 30L', 'Uso doméstico', 8, NOW(), NOW()),
('Saco de Lixo 50L', 'Mais resistente', 8, NOW(), NOW()),
('Saco de Lixo 100L', 'Grande volume', 8, NOW(), NOW()),
('Luvas de Limpeza', 'Proteção das mãos', 8, NOW(), NOW()),
('Bucha Vegetal', 'Limpeza leve', 8, NOW(), NOW()),
('Removedor Multiuso 1L', 'Limpeza pesada', 8, NOW(), NOW()),
('Inseticida Aerosol', 'Controle de insetos', 8, NOW(), NOW()),
('Desodorizador de Ambiente', 'Aroma agradável', 8, NOW(), NOW()),
('Álcool Líquido 70% 1L', 'Desinfecção', 8, NOW(), NOW()),
('Álcool Gel 500ml', 'Higienização rápida', 8, NOW(), NOW());

-- PETS 🐶
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Ração Cães Adultos 10kg', 'Alimento completo para cães', 9, NOW(), NOW()),
('Ração Cães Filhotes 3kg', 'Nutrição para crescimento', 9, NOW(), NOW()),
('Ração Cães Pequeno Porte 5kg', 'Cães de pequeno porte', 9, NOW(), NOW()),
('Ração Cães Grande Porte 15kg', 'Alta energia', 9, NOW(), NOW()),
('Ração Gatos Adultos 1kg', 'Nutrição felina', 9, NOW(), NOW()),
('Ração Gatos Filhotes 1kg', 'Crescimento saudável', 9, NOW(), NOW()),
('Ração Gatos Castrados', 'Controle de peso', 9, NOW(), NOW()),
('Petisco Cães Biscoito', 'Recompensa canina', 9, NOW(), NOW()),
('Petisco Cães Ossinho', 'Entretenimento e higiene dental', 9, NOW(), NOW()),
('Petisco Gatos Snacks', 'Agrados felinos', 9, NOW(), NOW()),
('Shampoo Pet Neutro', 'Banho de cães', 9, NOW(), NOW()),
('Shampoo Antipulgas Pet', 'Controle de parasitas', 9, NOW(), NOW()),
('Condicionador Pet', 'Pelagem macia', 9, NOW(), NOW()),
('Coleira Ajustável', 'Passeio seguro', 9, NOW(), NOW()),
('Guia para Cães', 'Controle no passeio', 9, NOW(), NOW()),
('Peitoral para Cães', 'Mais conforto', 9, NOW(), NOW()),
('Caminha Pet Pequena', 'Descanso confortável', 9, NOW(), NOW()),
('Caminha Pet Grande', 'Cães maiores', 9, NOW(), NOW()),
('Casinha para Cães', 'Abrigo externo', 9, NOW(), NOW()),
('Arranhador para Gatos', 'Entretenimento felino', 9, NOW(), NOW()),
('Areia Sanitária Gatos', 'Higiene felina', 9, NOW(), NOW()),
('Caixa de Areia', 'Uso de gatos', 9, NOW(), NOW()),
('Comedouro Plástico', 'Alimentação pet', 9, NOW(), NOW()),
('Comedouro Inox', 'Mais durável', 9, NOW(), NOW()),
('Bebedouro Automático Pet', 'Água sempre disponível', 9, NOW(), NOW()),
('Brinquedo Mordedor', 'Cães filhotes', 9, NOW(), NOW()),
('Brinquedo Bolinha', 'Diversão geral', 9, NOW(), NOW()),
('Brinquedo Interativo Gato', 'Estimulação felina', 9, NOW(), NOW()),
('Antipulgas Pipeta Cães', 'Proteção externa', 9, NOW(), NOW()),
('Antipulgas Pipeta Gatos', 'Proteção felina', 9, NOW(), NOW()),
('Vermífugo Cães', 'Controle interno', 9, NOW(), NOW()),
('Vermífugo Gatos', 'Saúde felina', 9, NOW(), NOW()),
('Tapete Higiênico Cães', 'Treinamento sanitário', 9, NOW(), NOW()),
('Escova para Pelos Pet', 'Higiene da pelagem', 9, NOW(), NOW()),
('Luvas de Escovação Pet', 'Remoção de pelos', 9, NOW(), NOW()),
('Spray Desodorante Pet', 'Cheiro agradável', 9, NOW(), NOW()),
('Cinto de Segurança Pet', 'Transporte seguro', 9, NOW(), NOW());

-- DOCES 🍬
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Chocolate ao Leite Barra 100g', 'Chocolate tradicional', 10, NOW(), NOW()),
('Chocolate Meio Amargo 100g', 'Menos açúcar', 10, NOW(), NOW()),
('Chocolate Branco 90g', 'Sabor suave', 10, NOW(), NOW()),
('Chocolate Recheado Avelã', 'Recheio cremoso', 10, NOW(), NOW()),
('Bombom Sortido 250g', 'Caixa variada', 10, NOW(), NOW()),
('Caixa de Bombons Premium', 'Seleção especial', 10, NOW(), NOW()),
('Bala de Morango 100g', 'Balas doces', 10, NOW(), NOW()),
('Bala de Hortelã 100g', 'Refrescante', 10, NOW(), NOW()),
('Bala de Caramelo', 'Clássica doce', 10, NOW(), NOW()),
('Pirulito Colorido', 'Doce infantil', 10, NOW(), NOW()),
('Pirulito Recheado', 'Com goma interna', 10, NOW(), NOW()),
('Chiclete Hortelã', 'Refrescante', 10, NOW(), NOW()),
('Chiclete Tutti-Frutti', 'Sabor frutado', 10, NOW(), NOW()),
('Chiclete com Recheio', 'Explosão de sabor', 10, NOW(), NOW()),
('Biscoito Recheado Chocolate', 'Crocante e doce', 10, NOW(), NOW()),
('Biscoito Recheado Morango', 'Sabor frutado', 10, NOW(), NOW()),
('Biscoito Wafer Chocolate', 'Camadas crocantes', 10, NOW(), NOW()),
('Biscoito Wafer Morango', 'Leve e doce', 10, NOW(), NOW()),
('Biscoito Coberto Chocolate', 'Extra doce', 10, NOW(), NOW()),
('Pudim Pronto Chocolate', 'Sobremesa gelada', 10, NOW(), NOW()),
('Pudim Pronto Baunilha', 'Sobremesa cremosa', 10, NOW(), NOW()),
('Mousse Chocolate Pronto', 'Sobremesa leve', 10, NOW(), NOW()),
('Gelatina Morango', 'Sobremesa simples', 10, NOW(), NOW()),
('Gelatina Uva', 'Sabor frutado', 10, NOW(), NOW()),
('Doce de Leite Pote', 'Tradicional brasileiro', 10, NOW(), NOW()),
('Paçoca Rolha', 'Amendoim doce', 10, NOW(), NOW()),
('Pé de Moleque', 'Doce de festa junina', 10, NOW(), NOW()),
('Brigadeiro Pronto', 'Doce de festa', 10, NOW(), NOW()),
('Beijinho de Coco', 'Doce tradicional', 10, NOW(), NOW()),
('Marshmallow 150g', 'Doce macio', 10, NOW(), NOW()),
('Chocolate Granulado', 'Uso culinário', 10, NOW(), NOW()),
('Chocolate em Pó Doce', 'Preparos caseiros', 10, NOW(), NOW()),
('Tablete de Chocolate Avelã', 'Recheado premium', 10, NOW(), NOW()),
('Chocolate Crocante Amendoim', 'Textura crocante', 10, NOW(), NOW());

-- UTILIDADES 🪛
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Fósforos Caixa', 'Uso doméstico', 11, NOW(), NOW()),
('Isqueiro Recarregável', 'Acendimento de fogão e velas', 11, NOW(), NOW()),
('Velas Brancas 8 unidades', 'Uso em falta de energia', 11, NOW(), NOW()),
('Velas Aromáticas', 'Ambiente perfumado', 11, NOW(), NOW()),
('Pilha AA 4 unidades', 'Uso geral', 11, NOW(), NOW()),
('Pilha AAA 4 unidades', 'Pequenos aparelhos', 11, NOW(), NOW()),
('Extensão Elétrica 3m', 'Aumento de tomadas', 11, NOW(), NOW()),
('Filtro de Linha 5 Tomadas', 'Proteção elétrica', 11, NOW(), NOW()),
('Lâmpada LED 9W', 'Economia de energia', 11, NOW(), NOW()),
('Lâmpada LED 12W', 'Alta luminosidade', 11, NOW(), NOW()),
('Fita Adesiva Transparente', 'Uso geral', 11, NOW(), NOW()),
('Fita Isolante', 'Instalações elétricas', 11, NOW(), NOW()),
('Super Cola Instantânea', 'Fixação rápida', 11, NOW(), NOW()),
('Cola Branca Escolar', 'Uso doméstico e escolar', 11, NOW(), NOW()),
('Tesoura Multiuso', 'Corte geral', 11, NOW(), NOW()),
('Estilete com Lâmina', 'Corte preciso', 11, NOW(), NOW()),
('Caneta Permanente Preta', 'Uso geral', 11, NOW(), NOW()),
('Caneta Esferográfica Azul', 'Escrita diária', 11, NOW(), NOW()),
('Caneta Esferográfica Preta', 'Escrita formal', 11, NOW(), NOW()),
('Lápis Preto Nº2', 'Uso escolar', 11, NOW(), NOW()),
('Apontador com Depósito', 'Uso escolar', 11, NOW(), NOW()),
('Borracha Branca', 'Apagar escrita', 11, NOW(), NOW()),
('Caderno 1 Matéria', 'Uso escolar', 11, NOW(), NOW()),
('Caderno 10 Matérias', 'Uso escolar', 11, NOW(), NOW()),
('Agenda Diária', 'Organização pessoal', 11, NOW(), NOW()),
('Sacola Reutilizável', 'Transporte de compras', 11, NOW(), NOW()),
('Organizador Plástico Pequeno', 'Armazenamento', 11, NOW(), NOW()),
('Organizador Plástico Grande', 'Organização doméstica', 11, NOW(), NOW()),
('Caixa Organizadora com Tampa', 'Armazenamento seguro', 11, NOW(), NOW()),
('Garrafa Plástica 1L', 'Uso diário', 11, NOW(), NOW()),
('Garrafa Térmica Simples', 'Conservação de líquidos', 11, NOW(), NOW()),
('Pano Multiuso Reutilizável', 'Limpeza leve', 11, NOW(), NOW()),
('Toalha de Mesa Plástica', 'Proteção de mesa', 11, NOW(), NOW()),
('Cortina de Banheiro Plástica', 'Proteção banheiro', 11, NOW(), NOW()),
('Trava de Segurança Infantil', 'Proteção doméstica', 11, NOW(), NOW()),
('Relógio de Parede Simples', 'Uso doméstico', 11, NOW(), NOW()),
('Ventilador Portátil USB', 'Resfriamento pessoal', 11, NOW(), NOW()),
('Adaptador de Tomada Universal', 'Compatibilidade elétrica', 11, NOW(), NOW()),
('Suporte para Celular', 'Uso em mesa ou carro', 11, NOW(), NOW()),
('Cabos USB Tipo C', 'Carregamento e dados', 11, NOW(), NOW()),
('Carregador de Celular', 'Energia para dispositivos', 11, NOW(), NOW());

-- BEBES 🍼
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Fralda Descartável RN', 'Recém-nascido', 12, NOW(), NOW()),
('Fralda Descartável P', 'Bebês pequenos', 12, NOW(), NOW()),
('Fralda Descartável M', 'Uso diário', 12, NOW(), NOW()),
('Fralda Descartável G', 'Maior absorção', 12, NOW(), NOW()),
('Fralda Descartável XG', 'Bebês maiores', 12, NOW(), NOW()),
('Lenço Umedecido 48 unidades', 'Higiene do bebê', 12, NOW(), NOW()),
('Lenço Umedecido 100 unidades', 'Uso prolongado', 12, NOW(), NOW()),
('Pomada para Assaduras', 'Proteção da pele', 12, NOW(), NOW()),
('Sabonete Infantil Líquido', 'Banho delicado', 12, NOW(), NOW()),
('Shampoo Infantil Suave', 'Sem irritar olhos', 12, NOW(), NOW()),
('Condicionador Infantil', 'Cabelos macios', 12, NOW(), NOW()),
('Colônia Infantil Suave', 'Cheiro leve', 12, NOW(), NOW()),
('Talco Infantil', 'Higiene e conforto', 12, NOW(), NOW()),
('Toalha Umedecida Refil', 'Reposição econômica', 12, NOW(), NOW()),
('Algodão Hidrófilo', 'Limpeza delicada', 12, NOW(), NOW()),
('Cotonete Infantil', 'Higiene segura', 12, NOW(), NOW()),
('Mamadeira 120ml', 'Alimentação inicial', 12, NOW(), NOW()),
('Mamadeira 240ml', 'Uso diário', 12, NOW(), NOW()),
('Mamadeira Anticólica', 'Reduz cólicas', 12, NOW(), NOW()),
('Bico de Silicone para Mamadeira', 'Reposição', 12, NOW(), NOW()),
('Chupeta Ortodôntica', 'Conforto do bebê', 12, NOW(), NOW()),
('Chupeta de Silicone', 'Uso diário', 12, NOW(), NOW()),
('Prendedor de Chupeta', 'Evita quedas', 12, NOW(), NOW()),
('Escova de Cabelo Infantil', 'Cuidado delicado', 12, NOW(), NOW()),
('Termômetro Digital Infantil', 'Controle de temperatura', 12, NOW(), NOW()),
('Banheira Infantil Plástica', 'Banho seguro', 12, NOW(), NOW()),
('Toalha com Capuz Bebê', 'Após o banho', 12, NOW(), NOW()),
('Cadeirinha de Alimentação', 'Refeições seguras', 12, NOW(), NOW()),
('Prato Infantil Antiderrapante', 'Alimentação independente', 12, NOW(), NOW()),
('Talher Infantil Silicone', 'Uso seguro', 12, NOW(), NOW()),
('Babador Impermeável', 'Evita sujeira', 12, NOW(), NOW()),
('Roupinha Bebê Body Manga Curta', 'Uso diário', 12, NOW(), NOW()),
('Roupinha Bebê Body Manga Longa', 'Proteção térmica', 12, NOW(), NOW()),
('Mijão Bebê Algodão', 'Conforto diário', 12, NOW(), NOW()),
('Cobertor Infantil Leve', 'Proteção contra frio', 12, NOW(), NOW()),
('Cobertor Bebê Fleece', 'Mais quente', 12, NOW(), NOW()),
('Mosquiteiro para Berço', 'Proteção contra insetos', 12, NOW(), NOW()),
('Kit Higiene Bebê', 'Conjunto completo', 12, NOW(), NOW());

-- SAZONAIS 🎉
INSERT INTO produto (nome, descricao, categoria_id, criado_em, atualizado_em) VALUES
('Ovos de Páscoa ao Leite 200g', 'Chocolate sazonal de Páscoa', 13, NOW(), NOW()),
('Ovos de Páscoa Recheado', 'Chocolate com recheio cremoso', 13, NOW(), NOW()),
('Coelho de Chocolate', 'Chocolate temático Páscoa', 13, NOW(), NOW()),
('Panetone Tradicional 500g', 'Natal clássico', 13, NOW(), NOW()),
('Panetone com Gotas de Chocolate', 'Versão doce de Natal', 13, NOW(), NOW()),
('Chocotone Recheado', 'Panetone com recheio', 13, NOW(), NOW()),
('Rabanada Pronta', 'Sobremesa natalina', 13, NOW(), NOW()),
('Biscoito Decorado Natalino', 'Temático de Natal', 13, NOW(), NOW()),
('Peru Congelado', 'Ceia de Natal', 13, NOW(), NOW()),
('Chester Congelado', 'Ceia festiva', 13, NOW(), NOW()),
('Tender Defumado', 'Carnes natalinas', 13, NOW(), NOW()),
('Sidra Espumante Sem Álcool', 'Bebida festiva', 13, NOW(), NOW()),
('Guirlanda Decorativa Natal', 'Decoração natalina', 13, NOW(), NOW()),
('Luzes Pisca-Pisca LED', 'Decoração de Natal', 13, NOW(), NOW()),
('Árvore de Natal 1,5m', 'Decoração principal', 13, NOW(), NOW()),
('Enfeites de Natal Sortidos', 'Decoração geral', 13, NOW(), NOW()),
('Colomba Pascal Tradicional', 'Doce de Páscoa', 13, NOW(), NOW()),
('Colomba Pascal Chocolate', 'Versão recheada', 13, NOW(), NOW()),
('Chocolate Ovo Infantil Surpresa', 'Brinquedo + chocolate', 13, NOW(), NOW()),
('Festa Junina Pipoca Doce', 'Sazonal junino', 13, NOW(), NOW()),
('Milho para Pipoca', 'Uso em festas juninas', 13, NOW(), NOW()),
('Pé de Moleque Festa Junina', 'Doce típico', 13, NOW(), NOW()),
('Paçoca Festa Junina', 'Amendoim doce', 13, NOW(), NOW()),
('Quentão Pronto Sem Álcool', 'Bebida junina', 13, NOW(), NOW()),
('Canjica Doce Pronta', 'Sobremesa junina', 13, NOW(), NOW()),
('Bandeirinhas Decorativas Juninas', 'Decoração festa junina', 13, NOW(), NOW()),
('Balão Decorativo Junino', 'Decoração ambiente', 13, NOW(), NOW()),
('Fogueira Decorativa LED', 'Simulação festa junina', 13, NOW(), NOW()),
('Sorvete Picolé Verão Sortido', 'Sazonal verão', 13, NOW(), NOW()),
('Água de Coco Natural', 'Refrescante verão', 13, NOW(), NOW()),
('Melancia Inteira', 'Fruta sazonal verão', 13, NOW(), NOW()),
('Uva Verde Premium', 'Fruta refrescante', 13, NOW(), NOW()),
('Caixa de Morango Fresco', 'Fruta de verão', 13, NOW(), NOW()),
('Chapéu de Praia', 'Acessório verão', 13, NOW(), NOW()),
('Boia Inflável Infantil', 'Diversão piscina', 13, NOW(), NOW()),
('Protetor Solar Promo Verão', 'Proteção sazonal', 13, NOW(), NOW());
